"""
Plot ground-truth error versus sparsity/angle for model1 and model2.

Expected CSVs are produced by main.py:
    results_csv/table3_model1_detail.csv
    results_csv/table4_model2_detail.csv

Plots generated by default (LBFGS stage only):
    1) model2: sparsity vs Absolute Error
    2) model2: sparsity vs Relative Error
    3) model1: sparsity-angle filled contour + contour overlay, Absolute Error
    4) model1: sparsity-angle filled contour + contour overlay, Relative Error

Why LBFGS is the default:
    verify.py checks the pruning mask specifically before/after LBFGS, and the
    supplied verification output shows every checked LBFGS checkpoint kept all
    pruned entries at numerical zero. The script still supports --stage train,
    --stage lbfgs, and --stage both.

Examples:
    python plot_error_vs_sparsity.py
    python plot_error_vs_sparsity.py --csv-dir results_csv --stage both
    python plot_error_vs_sparsity.py --metric both
    python plot_error_vs_sparsity.py --show
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm

REQUIRED_MODEL1 = {"Sparsity", "Angle", "Stage", "AbsErr", "RelErr_%", "nu"}
REQUIRED_MODEL2 = {"Sparsity", "Stage", "AbsErr", "RelErr_%", "nu"}


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Plot PINN sparsity/error results.")
    p.add_argument(
        "--csv-dir",
        type=Path,
        default=Path("results_csv"),
        help="Directory containing main.py CSV outputs (default: results_csv)",
    )
    p.add_argument(
        "--stage",
        choices=("train", "lbfgs", "both"),
        default="lbfgs",
        help="Checkpoint stage to plot (default: lbfgs)",
    )
    p.add_argument(
        "--metric",
        choices=("abs", "rel", "both"),
        default="both",
        help="Error metric(s) to plot (default: both)",
    )
    p.add_argument(
        "--out-dir",
        type=Path,
        default=Path("plots"),
        help="Directory for PNG output (default: plots)",
    )
    p.add_argument(
        "--show",
        action="store_true",
        help="Display figures interactively instead of only saving them.",
    )
    p.add_argument(
        "--dpi",
        type=int,
        default=220,
        help="Saved figure DPI (default: 220)",
    )
    return p.parse_args()


def require_columns(df: pd.DataFrame, required: set[str], path: Path) -> None:
    missing = sorted(required - set(df.columns))
    if missing:
        raise ValueError(
            f"{path} is missing required columns: {', '.join(missing)}\n"
            f"Found columns: {list(df.columns)}"
        )


def load_data(csv_dir: Path) -> tuple[pd.DataFrame, pd.DataFrame]:
    m1_path = csv_dir / "table3_model1_detail.csv"
    m2_path = csv_dir / "table4_model2_detail.csv"

    if not m1_path.exists() or not m2_path.exists():
        missing = [str(p) for p in (m1_path, m2_path) if not p.exists()]
        raise FileNotFoundError(
            "Could not find the required CSV output(s):\n  "
            + "\n  ".join(missing)
            + "\nRun main.py first, then run this plotting script."
        )

    m1 = pd.read_csv(m1_path)
    m2 = pd.read_csv(m2_path)

    require_columns(m1, REQUIRED_MODEL1, m1_path)
    require_columns(m2, REQUIRED_MODEL2, m2_path)

    # Numeric conversion makes the script tolerant of normal CSV formatting.
    for df in (m1, m2):
        for col in ("Sparsity", "AbsErr", "RelErr_%", "nu"):
            df[col] = pd.to_numeric(df[col], errors="coerce")
    m1["Angle"] = pd.to_numeric(m1["Angle"], errors="coerce")

    if m1[["Sparsity", "Angle", "AbsErr", "RelErr_%"]].isna().any().any():
        raise ValueError("model1 CSV contains non-numeric/empty values in plotting columns.")
    if m2[["Sparsity", "AbsErr", "RelErr_%"]].isna().any().any():
        raise ValueError("model2 CSV contains non-numeric/empty values in plotting columns.")

    return m1, m2


def filter_stage(df: pd.DataFrame, stage: str) -> pd.DataFrame:
    if stage == "both":
        out = df.copy()
    else:
        out = df[df["Stage"].astype(str).str.lower() == stage].copy()

    if out.empty:
        raise ValueError(f"No rows found for stage={stage!r}.")
    return out


def error_col(metric: str) -> str:
    return "AbsErr" if metric == "abs" else "RelErr_%"


def metric_label(metric: str) -> str:
    return "Absolute Error" if metric == "abs" else "Relative Error (%)"


def safe_name(s: str) -> str:
    out = s.lower().replace("%", "pct")
    out = "".join(ch if ch.isalnum() else "_" for ch in out)
    return "_".join(part for part in out.split("_") if part)


def savefig(fig: plt.Figure, out_path: Path, dpi: int, show: bool) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=dpi, bbox_inches="tight")
    print(f"[plot] wrote {out_path}")
    if show:
        plt.show()
    plt.close(fig)


def plot_model2(
    df: pd.DataFrame,
    metric: str,
    out_dir: Path,
    stage: str,
    dpi: int,
    show: bool,
) -> None:
    col = error_col(metric)
    label = metric_label(metric)

    # When --stage both is used, create one completely separate
    # figure for Adam/train and one completely separate figure for LBFGS.
    if stage == "both":
        stage_names = [
            str(s)
            for s in sorted(df["Stage"].dropna().unique())
        ]
    else:
        stage_names = [stage]

    for stage_name in stage_names:
        sub = df[
            df["Stage"].astype(str).str.lower() == stage_name.lower()
        ].copy()

        if sub.empty:
            print(f"[skip] model2 {label}: no data for stage={stage_name}")
            continue

        # One value per sparsity level.
        # Mean is only relevant if the CSV happens to contain duplicate
        # rows for the same sparsity.
        grouped = (
            sub.groupby("Sparsity", as_index=False)[col]
            .mean()
            .sort_values("Sparsity")
        )

        fig, ax = plt.subplots(figsize=(7.5, 5.3))

        ax.plot(
            grouped["Sparsity"],
            grouped[col],
            marker="o",
            linewidth=1.8,
            markersize=5,
        )

        ax.set_xlabel("Sparsity")
        ax.set_ylabel(label)
        ax.set_yscale("log")

        stage_label = (
            "Adam"
            if stage_name.lower() == "train"
            else "LBFGS"
            if stage_name.lower() == "lbfgs"
            else stage_name
        )

        ax.set_title(
            f"model2: {label} vs Sparsity\n{stage_label}"
        )

        ax.set_xticks(
            sorted(sub["Sparsity"].unique())
        )

        ax.grid(True, alpha=0.25)

        fig.tight_layout()

        filename = (
            f"model2_sparsity_vs_{safe_name(label)}_"
            f"{stage_name.lower()}.png"
        )

        savefig(
            fig,
            out_dir / filename,
            dpi,
            show,
        )

def _regularize_angle_grid(pivot: pd.DataFrame) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Return X=angles, Y=sparsities, Z=metric.

    Angles are irregular in the supplied experiment (e.g. 45/60/90), so do
    NOT pretend the spacing is uniform by using image/imshow coordinates.
    contourf accepts the actual angle coordinates.
    """
    pivot = pivot.sort_index().sort_index(axis=1)
    sparsities = pivot.index.to_numpy(float)
    angles = pivot.columns.to_numpy(float)
    Z = pivot.to_numpy(float)

    # If angle=0 exists, close the polar-like cycle at 360 for a visually
    # continuous boundary. This does not change any measured values.
    if np.isclose(angles[0], 0.0) and not np.isclose(angles[-1], 360.0):
        angles = np.append(angles, 360.0)
        Z = np.column_stack([Z, Z[:, 0]])

    return angles, sparsities, Z


def plot_model1_contour(
    df: pd.DataFrame,
    metric: str,
    out_dir: Path,
    stage: str,
    dpi: int,
    show: bool,
) -> None:
    col = error_col(metric)
    label = metric_label(metric)

    if stage == "both":
        stage_names = [str(s) for s in sorted(df["Stage"].dropna().unique())]
    else:
        stage_names = [stage]

    # Build every stage's pivot first so all of them can share one color
    # scale for this metric -- if each stage's LogNorm were fit to only its
    # own data (the previous behaviour), the same error value could land on
    # a different color in the Adam plot than in the LBFGS plot.
    pivots: dict[str, pd.DataFrame] = {}
    for stage_name in stage_names:
        sub = df[df["Stage"].astype(str).str.lower() == stage_name.lower()].copy()

        pivot = sub.pivot_table(
            index="Sparsity",
            columns="Angle",
            values=col,
            aggfunc="mean",
        )

        if pivot.empty:
            print(f"[skip] model1 {label}: no data for stage={stage_name}")
            continue

        pivots[stage_name] = pivot

    if not pivots:
        return

    all_vals = np.concatenate([p.to_numpy(float).ravel() for p in pivots.values()])
    all_vals = all_vals[np.isfinite(all_vals)]

    if all_vals.size == 0:
        raise ValueError(f"Non-finite {label} values in model1 data.")

    zmin = float(np.nanmin(all_vals))
    zmax = float(np.nanmax(all_vals))

    zmin = max(zmin, 1e-7)
    if zmax <= zmin:
        zmax = zmin * 10.0

    for stage_name, pivot in pivots.items():
        fig, ax = plt.subplots(figsize=(11.0, 5.5))  # Wider canvas

        # Shared vmin/vmax (computed above, across every stage plotted for
        # this metric) -- a fresh LogNorm per plot since Normalize objects
        # shouldn't be reused across multiple imshow/colorbar calls.
        im = ax.imshow(
            pivot.values,
            norm=LogNorm(vmin=zmin, vmax=zmax),
            cmap="viridis",
            aspect="auto",
            origin="lower",
        )

        # Colorbar
        cbar = fig.colorbar(im, ax=ax, pad=0.02)
        cbar.set_label(f"{label} (Log Scale)")

        # Map clean discrete tick labels
        ax.set_xticks(np.arange(len(pivot.columns)))
        ax.set_xticklabels([f"{int(a)}°" for a in pivot.columns], rotation=0)

        ax.set_yticks(np.arange(len(pivot.index)))
        ax.set_yticklabels([f"{s:.2f}" for s in pivot.index])

        ax.set_xlabel("Angle")
        ax.set_ylabel("Sparsity")
        ax.set_title(
            f"model1: {label} (Discrete Log Scale)\n"
            f"Sparsity × Angle ({stage_name})"
        )

        fig.tight_layout()

        filename = (
            f"model1_sparsity_angle_{safe_name(label)}_"
            f"{stage_name.lower()}.png"
        )
        savefig(fig, out_dir / filename, dpi, show)

def print_data_checks(m1: pd.DataFrame, m2: pd.DataFrame, stage: str) -> None:
    print("\n=== Data checks ===")

    for model_name, df in (("model1", m1), ("model2", m2)):
        sub = filter_stage(df, stage)

        print(
            f"{model_name}: {len(sub)} rows, "
            f"stages={sorted(map(str, sub['Stage'].unique()))}, "
            f"sparsities={sorted(sub['Sparsity'].unique())}"
        )

        if model_name == "model1":
            print(
                f"  angles={sorted(sub['Angle'].unique())}, "
                f"unique (sparsity, angle)={sub[['Sparsity','Angle']].drop_duplicates().shape[0]}"
            )
        else:
            print(
                f"  unique sparsity={sub['Sparsity'].nunique()}"
            )

        for metric in ("abs", "rel"):
            col = error_col(metric)
            vals = sub[col].to_numpy(float)
            print(
                f"  {metric_label(metric)}: min={np.nanmin(vals):.6g}, "
                f"median={np.nanmedian(vals):.6g}, max={np.nanmax(vals):.6g}"
            )

    # Basic physical/numerical sanity checks for the metric itself.
    if (m1["AbsErr"] < 0).any() or (m2["AbsErr"] < 0).any():
        raise ValueError("Absolute Error contains negative values; CSV/calculation is inconsistent.")
    if (m1["RelErr_%"] < 0).any() or (m2["RelErr_%"] < 0).any():
        raise ValueError("Relative Error contains negative values; CSV/calculation is inconsistent.")

    # main.py defines RE% = AE / nu_true * 100, so the ratio should be constant.
    ratio = np.concatenate([
        m1["RelErr_%"].to_numpy() / m1["AbsErr"].replace(0, np.nan).to_numpy(),
        m2["RelErr_%"].to_numpy() / m2["AbsErr"].replace(0, np.nan).to_numpy(),
    ])
    ratio = ratio[np.isfinite(ratio)]
    if ratio.size:
        print(
            f"  RelativeError_% / AbsoluteError consistency: "
            f"min={ratio.min():.6g}, max={ratio.max():.6g} "
            f"(expected 100/nu_true ≈ 31415.9)"
        )

    # model1 should contain one location per sparsity-angle pair per stage.
    dup_m1 = (
        m1.groupby(["Stage", "Sparsity", "Angle"]).size()
        .reset_index(name="n")
    )
    bad_dup = dup_m1[dup_m1["n"] > 1]
    if not bad_dup.empty:
        print(
            "  WARNING: model1 has duplicate (Stage, Sparsity, Angle) rows; "
            "the plotter will average them."
        )


def main() -> None:
    args = parse_args()
    m1, m2 = load_data(args.csv_dir)

    # Validate before plotting.
    print_data_checks(m1, m2, args.stage)

    m1p = filter_stage(m1, args.stage)
    m2p = filter_stage(m2, args.stage)

    metrics = ("abs", "rel") if args.metric == "both" else (args.metric,)

    args.out_dir.mkdir(parents=True, exist_ok=True)

    for metric in metrics:
        plot_model2(m2p, metric, args.out_dir, args.stage, args.dpi, args.show)
        plot_model1_contour(m1p, metric, args.out_dir, args.stage, args.dpi, args.show)

    print(f"\nDone. Figures are in: {args.out_dir.resolve()}")


if __name__ == "__main__":
    main()
